// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htmkiekweguvkknciabk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0bWtpZWt3ZWd1dmtrbmNpYWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDI4NDksImV4cCI6MjA3MTIxODg0OX0.deaVI4lrksOs3la-yUzVHmNDhGSXM531S8Vn8GhrwNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});